/* Finance track. Vendor-neutral concepts; NetSuite used as the running ERP example.
   lvl: F foundation, P practitioner, A architect, L leader */
window.TRACKS = window.TRACKS || {};
window.TRACKS.finance = {
  id: "finance",
  name: "Finance",
  blurb: "Two things a technology leader needs and most never learn: how a financial system actually works underneath, and how money is argued about above it.",
  modules: [
    {
      id: "erp",
      name: "ERP and financial systems",
      blurb: "What the boxes in an ERP diagram actually contain. NetSuite is the running example; the concepts transfer to SAP, Oracle Fusion and Dynamics.",
      lessons: [
        { id: "erp1", t: "Chart of accounts", lvl: "F", k: ["Every posting lands in one account: asset, liability, equity, income or expense", "Account number ranges encode the type; the range scheme is a design decision", "Parent-child accounts drive report rollups, not just tidiness", "Adding accounts casually is how reporting dies over five years"], do: "Write the five account types and one example of each from your own company's spend." },
        { id: "erp2", t: "Double entry and the general ledger", lvl: "F", k: ["Every transaction has equal debits and credits, always", "The GL is the append-only truth; subledgers feed it", "Journal entries are the manual escape hatch and the audit magnet", "Reversing entries handle accruals that will be replaced by real invoices"], do: "Journalise one office rent payment as debit and credit lines." },
        { id: "erp3", t: "Subledgers and posting", lvl: "F", k: ["AP, AR, inventory and fixed assets are subledgers with their own detail", "Subledger totals must reconcile to their GL control accounts", "Integration bugs usually show up as subledger-to-GL variance", "Never let an integration write directly to the GL if a subledger exists"], do: "Name which subledger a customer invoice, a vendor bill and a depreciation run each touch." },
        { id: "erp4", t: "Segments: subsidiary, department, class, location", lvl: "F", k: ["Segments slice the same posting for different reporting views", "Subsidiary is legal; department and class are managerial", "Mandatory segments on every line is a governance decision made early or regretted late", "Segment sprawl makes consolidation slow and dashboards wrong"], do: "Sketch the segment set you would enforce for a services firm with three countries." },
        { id: "erp5", t: "Multi-subsidiary and consolidation", lvl: "P", k: ["Each legal entity keeps its own books; consolidation rolls them up", "Ownership percentage and elimination rules drive the roll-up", "Consolidated exchange rates differ from transaction rates", "Statutory reporting per entity coexists with management reporting across entities"], do: "List which reports must exist per entity versus only at group level." },
        { id: "erp6", t: "Multi-book accounting", lvl: "A", k: ["One transaction can post differently to primary and secondary books", "Used for local GAAP versus IFRS, or tax versus management views", "Book-specific rules apply to depreciation, revenue and FX", "Integrations must know which book they are reading or they report nonsense"], do: "Identify one rule that would differ between a local GAAP book and IFRS." },
        { id: "erp7", t: "Procure to pay, end to end", lvl: "F", k: ["Requisition, approval, purchase order, receipt, vendor bill, payment", "Three-way match compares PO, receipt and bill before payment", "Accruals cover received-but-not-invoiced at period end", "Most P2P integration pain is receipt timing, not the invoice itself"], do: "Draw the six P2P steps and mark which two create GL postings." },
        { id: "erp8", t: "Order to cash, end to end", lvl: "F", k: ["Quote, sales order, fulfilment or delivery, invoice, cash application", "Revenue and receivable are recognised at invoice, not at cash", "Credit memos reverse; they do not delete", "Cash application matching is where automation pays back fastest"], do: "Trace one of your own product or service sales through all five steps." },
        { id: "erp9", t: "Accounts payable mechanics", lvl: "P", k: ["Vendor master data quality determines duplicate-payment risk", "Payment terms and early-payment discounts have real cash value", "Approval matrices encode delegation of authority", "Payment batches, not individual payments, are the operational unit"], do: "Write the approval thresholds you would set for bills at three value bands." },
        { id: "erp10", t: "Accounts receivable and collections", lvl: "P", k: ["Ageing buckets drive collections priority and bad-debt provisioning", "DSO measures how long revenue takes to become cash", "Disputes park an invoice without deleting the receivable", "Write-offs need authority levels, not just a button"], do: "Compute DSO from a receivables balance and quarterly revenue figure." },
        { id: "erp11", t: "Revenue recognition under ASC 606", lvl: "A", k: ["Five steps: contract, obligations, price, allocation, recognition", "Revenue is recognised as obligations are satisfied, not when cash arrives", "Software and services contracts split into multiple obligations", "This is where finance and engineering disagree most about what shipped"], do: "Split a hypothetical licence-plus-implementation deal into performance obligations." },
        { id: "erp12", t: "Deferred revenue schedules", lvl: "A", k: ["Unearned revenue is a liability until the obligation is met", "Schedules spread recognition over time or milestones", "Contract modifications force schedule rebuilds, not edits", "Deferred revenue balance is a leading indicator of future revenue"], do: "Build a twelve-month straight-line schedule for an annual subscription." },
        { id: "erp13", t: "Record to report and month-end close", lvl: "P", k: ["Sub-ledger cutoffs, accruals, reconciliations, adjustments, then reporting", "A close calendar assigns owner and deadline to each task", "Period lock prevents backdated postings after sign-off", "Close duration is the honest measure of finance systems health"], do: "List the close tasks that depend on data your integrations produce." },
        { id: "erp14", t: "Reconciliations", lvl: "P", k: ["Bank, intercompany, subledger-to-GL and clearing accounts each reconcile differently", "Unreconciled items ageing past a period is a control failure", "Suspense and clearing accounts should trend to zero", "Automated matching still needs a documented exception path"], do: "Pick one clearing account and define what a zero balance would prove." },
        { id: "erp15", t: "Fixed assets and depreciation", lvl: "P", k: ["Capitalisation threshold decides asset versus expense", "Useful life and method (straight line, reducing balance) drive the schedule", "Disposals create gain or loss, not just deletion", "Asset registers drift from reality without physical verification"], do: "Depreciate a 500,000 asset over five years straight line and state year-three book value." },
        { id: "erp16", t: "Inventory and cost of goods sold", lvl: "P", k: ["FIFO, weighted average and standard costing give different COGS from the same movements", "Landed cost pushes freight and duty into inventory value", "Variance accounts absorb the difference between standard and actual", "Stock counts and adjustments are the reconciliation of the physical world"], do: "Compute COGS for three purchases at different prices under FIFO and weighted average." },
        { id: "erp17", t: "Intercompany transactions and elimination", lvl: "A", k: ["Selling between your own entities creates matched receivable and payable", "Group accounts must eliminate both sides or revenue is overstated", "Transfer pricing sets the rate and attracts tax scrutiny", "Mismatched intercompany balances are a classic close blocker"], do: "Explain why unconsolidated intercompany sales inflate group revenue." },
        { id: "erp18", t: "Multi-currency and FX revaluation", lvl: "A", k: ["Transaction, functional and reporting currency are three different things", "Realised gain or loss happens at settlement; unrealised at revaluation", "Rate types differ: spot, average, historical, closing", "Integrations that store only base-currency amounts destroy auditability"], do: "State which currency amounts an integration must carry to remain auditable." },
        { id: "erp19", t: "Tax determination and compliance", lvl: "A", k: ["Tax depends on jurisdiction, product type, customer status and place of supply", "Indirect tax (GST, VAT) flows through separate liability accounts", "Withholding tax reduces payment but not the expense", "Tax engines exist because hardcoded rates always go stale"], do: "List three inputs a tax engine needs that a simple rate table lacks." },
        { id: "erp20", t: "Banking, payments and cash management", lvl: "P", k: ["Payment file formats and banking protocols are integration surface", "Positive pay and payment approval reduce fraud exposure", "Bank feeds automate statement import and matching", "Cash forecasting combines AR ageing, AP schedule and committed spend"], do: "Sketch the data a thirteen-week cash forecast needs and where each item lives." },
        { id: "erp21", t: "Project accounting and time capture", lvl: "P", k: ["Projects carry budget, actuals, billing rules and revenue rules separately", "Time and expense entries become both cost and billable revenue", "Percentage of completion recognises revenue against effort or cost", "Unbilled and unapproved time is the biggest hidden margin leak"], do: "Trace one timesheet entry from capture to invoice to revenue." },
        { id: "erp22", t: "Approval workflows and delegation of authority", lvl: "P", k: ["Authority matrices define who approves what at which value", "Delegation during absence must be explicit and logged", "Workflow bypasses are audit findings waiting to happen", "Approval latency is a real cost, not a compliance detail"], do: "Design an approval chain for a 2,000,000 capital purchase." },
        { id: "erp23", t: "Segregation of duties", lvl: "A", k: ["The same person must not create a vendor and pay it", "Role design, not user-by-user permissions, is the control", "Conflict matrices identify toxic role combinations", "Integration service accounts are the most commonly ignored SoD hole"], do: "Name three role pairs that should never sit with one person." },
        { id: "erp24", t: "Audit trail and internal controls", lvl: "A", k: ["Every field change should be attributable, timestamped and immutable", "Controls are preventive, detective or corrective", "External audit tests a sample and infers the whole", "Automated processes need control evidence too, not just people"], do: "Decide what evidence proves your integration did not alter a posted amount." },
        { id: "erp25", t: "Saved searches versus analytics datasets", lvl: "P", k: ["Operational lists and analytical aggregation are different tools", "Search results reflect permissions of the running user", "Heavy saved searches become the accidental reporting layer and then the bottleneck", "Anything reused twice should move to a governed dataset"], do: "Identify one report in your world that outgrew its query tool." },
        { id: "erp26", t: "SuiteQL and ERP record schemas", lvl: "A", k: ["ERP records are relational underneath, with internal ids everywhere", "Transaction, transaction line and entity are the core join spine", "Custom fields land in their own columns or tables depending on platform", "Query directly and you inherit undocumented schema changes on upgrade"], do: "Write a query shape joining transactions, lines and customers conceptually." },
        { id: "erp27", t: "ERP integration patterns", lvl: "A", k: ["REST, SOAP, scripted endpoints and file-based batch each have different limits", "Governance and concurrency limits cap throughput; design for them", "Idempotency keys prevent duplicate financial postings on retry", "Error queues with human review beat silent retries for money movement"], do: "Design retry behaviour for a payment posting that may already have succeeded." },
        { id: "erp28", t: "Data migration into an ERP", lvl: "A", k: ["Open items, balances and history are three separate migration decisions", "Migrate open transactions and balances; archive history elsewhere", "Reconcile migrated balances to the legacy trial balance before go-live", "Every migration needs a rollback point and a cutover freeze"], do: "Write the cutover sequence for a general-ledger migration weekend." }
      ]
    },
    {
      id: "fin",
      name: "Finance for engineering leaders",
      blurb: "The financial argument, not the bookkeeping. This is the module that separates architects from technology executives.",
      lessons: [
        { id: "fin1", t: "Reading a profit and loss statement", lvl: "F", k: ["Revenue, cost of revenue, gross profit, operating expense, operating income", "Gross margin shows delivery efficiency; operating margin shows the whole business", "Where your team's cost sits changes the story told about it", "Trends across periods matter more than any single period"], do: "Find any public company's P&L and compute its gross margin." },
        { id: "fin2", t: "Reading a balance sheet", lvl: "F", k: ["Assets equal liabilities plus equity, at a point in time", "Working capital is current assets minus current liabilities", "Deferred revenue is a liability that is good news", "Capitalised software sits here, not in the P&L"], do: "Classify five items from your company's world as asset, liability or equity." },
        { id: "fin3", t: "Reading a cash flow statement", lvl: "F", k: ["Operating, investing and financing are three separate stories", "Profit and cash differ because of timing, accruals and capex", "Free cash flow is what actually funds discretionary spending", "A profitable company can still run out of cash"], do: "Explain how a company can post profit and negative operating cash flow." },
        { id: "fin4", t: "How the three statements connect", lvl: "P", k: ["Net income flows to equity and starts the cash flow statement", "Depreciation is a P&L expense that adds back in cash flow", "Capex hits the balance sheet and cash flow, not the P&L directly", "Modelling one statement without the others produces fiction"], do: "Trace one 100,000 server purchase across all three statements." },
        { id: "fin5", t: "Bookings, billings, revenue and cash", lvl: "P", k: ["Bookings are signed; billings are invoiced; revenue is earned; cash is received", "Executives conflate these constantly, and the gap hides risk", "Backlog is booked work not yet recognised", "Ask which of the four a number refers to before reacting to it"], do: "Order the four for a three-year contract billed annually in advance." },
        { id: "fin6", t: "Gross margin and how engineering moves it", lvl: "P", k: ["Cost of revenue includes delivery staff, hosting and third-party licences", "Automation reduces cost of revenue; headcount growth increases it", "Margin improvement is the most defensible engineering business case", "A one-point margin gain on large revenue beats most feature work"], do: "Estimate the margin effect of automating one recurring manual process." },
        { id: "fin7", t: "Capex versus opex", lvl: "P", k: ["Capex is spent once and expensed over years; opex hits immediately", "Cloud shifted technology spend from capex to opex, changing the approval path", "Capex protects near-term operating income; opex preserves flexibility", "Which budget a project draws from often decides whether it happens"], do: "Classify five items in your current technology spend." },
        { id: "fin8", t: "Software capitalisation", lvl: "A", k: ["Development costs in the application phase can be capitalised; research cannot", "Capitalising spreads cost across years and improves current-year profit", "It requires evidence: stage gates, time tracking, project separation", "The rules push architecture toward projects with defensible boundaries"], do: "Split one project's activities into capitalisable and non-capitalisable." },
        { id: "fin9", t: "Unit economics", lvl: "P", k: ["Pick the unit: transaction, tenant, user, invoice, integration run", "Cost per unit exposes what aggregate spend hides", "Unit cost trending down is the strongest platform argument you can make", "If you cannot compute cost per unit, you cannot defend the platform"], do: "Define the right unit for your platform and estimate its current cost." },
        { id: "fin10", t: "Total cost of ownership", lvl: "P", k: ["Licence, infrastructure, implementation, run, support, exit", "Exit cost is routinely ignored and routinely decisive", "Compare over the same horizon or the comparison is dishonest", "Internal effort is a real cost even when no invoice exists"], do: "Build a five-year TCO comparison for one build-versus-buy choice you face." },
        { id: "fin11", t: "Time value of money: NPV, IRR, payback", lvl: "A", k: ["Money now is worth more than money later; discount rate quantifies it", "NPV above zero means it beats the hurdle rate", "IRR is the implied return; payback is how long capital is at risk", "Executives ask for payback first and NPV second"], do: "Compute simple payback for an automation costing 1,000,000 saving 40,000 monthly." },
        { id: "fin12", t: "Writing a business case", lvl: "A", k: ["Problem, options considered, recommendation, cost, benefit, risk, decision needed", "Quantify benefits in the same units finance already uses", "State the do-nothing option honestly; it is sometimes right", "One page for the decision; appendix for the analysis"], do: "Compress one current technical proposal to a single-page business case." },
        { id: "fin13", t: "Budget cycles and annual planning", lvl: "P", k: ["Planning starts months before the year and locks earlier than you expect", "Run-rate versus discretionary spend are argued differently", "Unspent budget is usually lost, which drives bad Q4 behaviour", "Missing the planning window costs a full year of funding"], do: "Find your organisation's planning calendar and mark the input deadline." },
        { id: "fin14", t: "Forecasting and variance analysis", lvl: "A", k: ["Forecast accuracy is trusted more than forecast optimism", "Variance is explained by price, volume or mix", "Repeated favourable variance means the budget was padded", "Explain variance before you are asked, in writing"], do: "Write a three-line variance explanation for a 20 percent cost overrun." },
        { id: "fin15", t: "Fully loaded cost of headcount", lvl: "P", k: ["Salary plus benefits, tax, tooling, facilities, management overhead", "Loaded cost is commonly 1.3 to 1.8 times salary", "Blended rate averages seniority across a delivery team", "Comparing a vendor rate to a salary is a category error"], do: "Estimate the loaded cost of one engineer in your own market." },
        { id: "fin16", t: "Services economics: utilisation and realisation", lvl: "A", k: ["Utilisation is billable hours over available hours", "Realisation is billed value over standard value; discounts destroy it", "Bench cost is fixed while revenue is variable, which drives urgency", "A few points of utilisation moves margin more than most cost cutting"], do: "Compute gross margin for an engineer at 75 percent utilisation and a given bill rate." },
        { id: "fin17", t: "The pyramid and delivery leverage", lvl: "A", k: ["Ratio of junior to senior staff determines cost per delivered hour", "Top-heavy teams deliver quality at unsustainable margin", "Leverage only works if seniors can actually delegate", "Automation changes the achievable pyramid shape, which is the AI argument"], do: "Design a ten-person team shape for a fixed-price engagement and justify it." },
        { id: "fin18", t: "Contract types and risk transfer", lvl: "A", k: ["Time and materials puts risk on the client; fixed price on the vendor", "Outcome and managed-service pricing shifts risk to whoever controls delivery", "Change control is what makes fixed price survivable", "Never accept fixed price on a scope you cannot bound"], do: "Pick the right contract type for a vague discovery engagement and defend it." },
        { id: "fin19", t: "Pricing a deal", lvl: "L", k: ["Cost plus target margin, then tested against what the market will pay", "Contingency covers estimation risk; discount erodes it directly", "Multi-year deals need escalation clauses or margin decays with inflation", "The technical leader's job is defending the estimate, not the discount"], do: "Price a six-month engagement bottom-up and state your walk-away margin." },
        { id: "fin20", t: "FinOps: showback and chargeback", lvl: "P", k: ["Tagging discipline is the precondition for any cost attribution", "Showback informs; chargeback changes behaviour and creates arguments", "Shared costs need an allocation rule agreed before the first bill", "Untagged spend above a few percent invalidates the whole exercise"], do: "Define the minimum tag set you would enforce on every cloud resource." },
        { id: "fin21", t: "FinOps: commitments and rate optimisation", lvl: "A", k: ["Reservations and savings plans trade flexibility for a lower rate", "Commit to the stable baseline, run the variable layer on demand", "Rightsizing and scheduling beat rate discounts on immature estates", "Commitment coverage and utilisation are the two numbers to watch"], do: "Identify which of your workloads are stable enough to commit." },
        { id: "fin22", t: "Cost anomaly governance", lvl: "P", k: ["Budgets with alerts catch runaway spend before the invoice does", "Anomaly detection needs an owner or alerts become noise", "Non-production environments are the usual source of surprise", "A monthly cost review with named owners beats any dashboard"], do: "Set the alert thresholds you would use for a non-production subscription." },
        { id: "fin23", t: "Presenting numbers to a CFO", lvl: "L", k: ["Lead with the number and the decision needed, not the method", "Show the assumption that would change the answer if wrong", "Use their vocabulary: margin, payback, run rate, risk", "Never present a benefit you cannot be measured on later"], do: "Rewrite your last technical update as three sentences a CFO would act on." }
      ]
    }
  ]
};
