/* Finance track. Vendor-neutral concepts; NetSuite used as the running ERP example.
   lvl: F foundation, P practitioner, A architect, L leader */
window.TRACKS = window.TRACKS || {};
window.TRACKS.finance = {
  id: "finance",
  name: "Finance",
  blurb: "Two things a technology leader needs and most never learn: how a financial system actually works underneath, and how money is argued about above it.",
  modules: [
    {
      id: "erp",
      name: "ERP and financial systems",
      blurb: "What the boxes in an ERP diagram actually contain. NetSuite is the running example; the concepts transfer to SAP, Oracle Fusion and Dynamics.",
      lessons: [
        { id: "erp1", t: "Chart of accounts", lvl: "F", k: ["Every posting lands in one account: asset, liability, equity, income or expense", "Account number ranges encode the type; the range scheme is a design decision", "Parent-child accounts drive report rollups, not just tidiness", "Adding accounts casually is how reporting dies over five years"], do: "Write the five account types and one example of each from your own company's spend." },
        { id: "erp2", t: "Double entry and the general ledger", lvl: "F", k: ["Every transaction has equal debits and credits, always", "The GL is the append-only truth; subledgers feed it", "Journal entries are the manual escape hatch and the audit magnet", "Reversing entries handle accruals that will be replaced by real invoices"], do: "Journalise one office rent payment as debit and credit lines." },
        { id: "erp3", t: "Subledgers and posting", lvl: "F", k: ["AP, AR, inventory and fixed assets are subledgers with their own detail", "Subledger totals must reconcile to their GL control accounts", "Integration bugs usually show up as subledger-to-GL variance", "Never let an integration write directly to the GL if a subledger exists"], do: "Name which subledger a customer invoice, a vendor bill and a depreciation run each touch." },
        { id: "erp4", t: "Segments: subsidiary, department, class, location", lvl: "F", k: ["Segments slice the same posting for different reporting views", "Subsidiary is legal; department and class are managerial", "Mandatory segments on every line is a governance decision made early or regretted late", "Segment sprawl makes consolidation slow and dashboards wrong"], do: "Sketch the segment set you would enforce for a services firm with three countries." },
        { id: "erp5", t: "Multi-subsidiary and consolidation", lvl: "P", k: ["Each legal entity keeps its own books; consolidation rolls them up", "Ownership percentage and elimination rules drive the roll-up", "Consolidated exchange rates differ from transaction rates", "Statutory reporting per entity coexists with management reporting across entities"], do: "List which reports must exist per entity versus only at group level." },
        { id: "erp6", t: "Multi-book accounting", lvl: "A", k: ["One transaction can post differently to primary and secondary books", "Used for local GAAP versus IFRS, or tax versus management views", "Book-specific rules apply to depreciation, revenue and FX", "Integrations must know which book they are reading or they report nonsense"], do: "Identify one rule that would differ between a local GAAP book and IFRS." },
        { id: "erp7", t: "Procure to pay, end to end", lvl: "F", k: ["Requisition, approval, purchase order, receipt, vendor bill, payment", "Three-way match compares PO, receipt and bill before payment", "Accruals cover received-but-not-invoiced at period end", "Most P2P integration pain is receipt timing, not the invoice itself"], do: "Draw the six P2P steps and mark which two create GL postings." },
        { id: "erp8", t: "Order to cash, end to end", lvl: "F", k: ["Quote, sales order, fulfilment or delivery, invoice, cash application", "Revenue and receivable are recognised at invoice, not at cash", "Credit memos reverse; they do not delete", "Cash application matching is where automation pays back fastest"], do: "Trace one of your own product or service sales through all five steps." },
        { id: "erp9", t: "Accounts payable mechanics", lvl: "P", k: ["Vendor master data quality determines duplicate-payment risk", "Payment terms and early-payment discounts have real cash value", "Approval matrices encode delegation of authority", "Payment batches, not individual payments, are the operational unit"], do: "Write the approval thresholds you would set for bills at three value bands." },
        { id: "erp10", t: "Accounts receivable and collections", lvl: "P", k: ["Ageing buckets drive collections priority and bad-debt provisioning", "DSO measures how long revenue takes to become cash", "Disputes park an invoice without deleting the receivable", "Write-offs need authority levels, not just a button"], do: "Compute DSO from a receivables balance and quarterly revenue figure." },
        { id: "erp11", t: "Revenue recognition under ASC 606", lvl: "A", k: ["Five steps: contract, obligations, price, allocation, recognition", "Revenue is recognised as obligations are satisfied, not when cash arrives", "Software and services contracts split into multiple obligations", "This is where finance and engineering disagree most about what shipped"], do: "Split a hypothetical licence-plus-implementation deal into performance obligations." },
        { id: "erp12", t: "Deferred revenue schedules", lvl: "A", k: ["Unearned revenue is a liability until the obligation is met", "Schedules spread recognition over time or milestones", "Contract modifications force schedule rebuilds, not edits", "Deferred revenue balance is a leading indicator of future revenue"], do: "Build a twelve-month straight-line schedule for an annual subscription." },
        { id: "erp13", t: "Record to report and month-end close", lvl: "P", k: ["Sub-ledger cutoffs, accruals, reconciliations, adjustments, then reporting", "A close calendar assigns owner and deadline to each task", "Period lock prevents backdated postings after sign-off", "Close duration is the honest measure of finance systems health"], do: "List the close tasks that depend on data your integrations produce." },
        { id: "erp14", t: "Reconciliations", lvl: "P", k: ["Bank, intercompany, subledger-to-GL and clearing accounts each reconcile differently", "Unreconciled items ageing past a period is a control failure", "Suspense and clearing accounts should trend to zero", "Automated matching still needs a documented exception path"], do: "Pick one clearing account and define what a zero balance would prove." },
        { id: "erp15", t: "Fixed assets and depreciation", lvl: "P", k: ["Capitalisation threshold decides asset versus expense", "Useful life and method (straight line, reducing balance) drive the schedule", "Disposals create gain or loss, not just deletion", "Asset registers drift from reality without physical verification"], do: "Depreciate a 500,000 asset over five years straight line and state year-three book value." },
        { id: "erp16", t: "Inventory and cost of goods sold", lvl: "P", k: ["FIFO, weighted average and standard costing give different COGS from the same movements", "Landed cost pushes freight and duty into inventory value", "Variance accounts absorb the difference between standard and actual", "Stock counts and adjustments are the reconciliation of the physical world"], do: "Compute COGS for three purchases at different prices under FIFO and weighted average." },
        { id: "erp17", t: "Intercompany transactions and elimination", lvl: "A", k: ["Selling between your own entities creates matched receivable and payable", "Group accounts must eliminate both sides or revenue is overstated", "Transfer pricing sets the rate and attracts tax scrutiny", "Mismatched intercompany balances are a classic close blocker"], do: "Explain why unconsolidated intercompany sales inflate group revenue." },
        { id: "erp18", t: "Multi-currency and FX revaluation", lvl: "A", k: ["Transaction, functional and reporting currency are three different things", "Realised gain or loss happens at settlement; unrealised at revaluation", "Rate types differ: spot, average, historical, closing", "Integrations that store only base-currency amounts destroy auditability"], do: "State which currency amounts an integration must carry to remain auditable." },
        { id: "erp19", t: "Tax determination and compliance", lvl: "A", k: ["Tax depends on jurisdiction, product type, customer status and place of supply", "Indirect tax (GST, VAT) flows through separate liability accounts", "Withholding tax reduces payment but not the expense", "Tax engines exist because hardcoded rates always go stale"], do: "List three inputs a tax engine needs that a simple rate table lacks." },
        { id: "erp20", t: "Banking, payments and cash management", lvl: "P", k: ["Payment file formats and banking protocols are integration surface", "Positive pay and payment approval reduce fraud exposure", "Bank feeds automate statement import and matching", "Cash forecasting combines AR ageing, AP schedule and committed spend"], do: "Sketch the data a thirteen-week cash forecast needs and where each item lives." },
        { id: "erp21", t: "Project accounting and time capture", lvl: "P", k: ["Projects carry budget, actuals, billing rules and revenue rules separately", "Time and expense entries become both cost and billable revenue", "Percentage of completion recognises revenue against effort or cost", "Unbilled and unapproved time is the biggest hidden margin leak"], do: "Trace one timesheet entry from capture to invoice to revenue." },
        { id: "erp22", t: "Approval workflows and delegation of authority", lvl: "P", k: ["Authority matrices define who approves what at which value", "Delegation during absence must be explicit and logged", "Workflow bypasses are audit findings waiting to happen", "Approval latency is a real cost, not a compliance detail"], do: "Design an approval chain for a 2,000,000 capital purchase." },
        { id: "erp23", t: "Segregation of duties", lvl: "A", k: ["The same person must not create a vendor and pay it", "Role design, not user-by-user permissions, is the control", "Conflict matrices identify toxic role combinations", "Integration service accounts are the most commonly ignored SoD hole"], do: "Name three role pairs that should never sit with one person." },
        { id: "erp24", t: "Audit trail and internal controls", lvl: "A", k: ["Every field change should be attributable, timestamped and immutable", "Controls are preventive, detective or corrective", "External audit tests a sample and infers the whole", "Automated processes need control evidence too, not just people"], do: "Decide what evidence proves your integration did not alter a posted amount." },
        { id: "erp25", t: "Saved searches versus analytics datasets", lvl: "P", k: ["Operational lists and analytical aggregation are different tools", "Search results reflect permissions of the running user", "Heavy saved searches become the accidental reporting layer and then the bottleneck", "Anything reused twice should move to a governed dataset"], do: "Identify one report in your world that outgrew its query tool." },
        { id: "erp26", t: "SuiteQL and ERP record schemas", lvl: "A", k: ["ERP records are relational underneath, with internal ids everywhere", "Transaction, transaction line and entity are the core join spine", "Custom fields land in their own columns or tables depending on platform", "Query directly and you inherit undocumented schema changes on upgrade"], do: "Write a query shape joining transactions, lines and customers conceptually." },
        { id: "erp27", t: "ERP integration patterns", lvl: "A", k: ["REST, SOAP, scripted endpoints and file-based batch each have different limits", "Governance and concurrency limits cap throughput; design for them", "Idempotency keys prevent duplicate financial postings on retry", "Error queues with human review beat silent retries for money movement"], do: "Design retry behaviour for a payment posting that may already have succeeded." },
        { id: "erp28", t: "Data migration into an ERP", lvl: "A", k: ["Open items, balances and history are three separate migration decisions", "Migrate open transactions and balances; archive history elsewhere", "Reconcile migrated balances to the legacy trial balance before go-live", "Every migration needs a rollback point and a cutover freeze"], do: "Write the cutover sequence for a general-ledger migration weekend." }
      ]
    },
    {
      id: "fin",
      name: "Finance for engineering leaders",
      blurb: "The financial argument, not the bookkeeping. This is the module that separates architects from technology executives.",
      lessons: [
        { id: "fin1", t: "Reading a profit and loss statement", lvl: "F", k: ["Revenue, cost of revenue, gross profit, operating expense, operating income", "Gross margin shows delivery efficiency; operating margin shows the whole business", "Where your team's cost sits changes the story told about it", "Trends across periods matter more than any single period"], do: "Find any public company's P&L and compute its gross margin." },
        { id: "fin2", t: "Reading a balance sheet", lvl: "F", k: ["Assets equal liabilities plus equity, at a point in time", "Working capital is current assets minus current liabilities", "Deferred revenue is a liability that is good news", "Capitalised software sits here, not in the P&L"], do: "Classify five items from your company's world as asset, liability or equity." },
        { id: "fin3", t: "Reading a cash flow statement", lvl: "F", k: ["Operating, investing and financing are three separate stories", "Profit and cash differ because of timing, accruals and capex", "Free cash flow is what actually funds discretionary spending", "A profitable company can still run out of cash"], do: "Explain how a company can post profit and negative operating cash flow." },
        { id: "fin4", t: "How the three statements connect", lvl: "P", k: ["Net income flows to equity and starts the cash flow statement", "Depreciation is a P&L expense that adds back in cash flow", "Capex hits the balance sheet and cash flow, not the P&L directly", "Modelling one statement without the others produces fiction"], do: "Trace one 100,000 server purchase across all three statements." },
        { id: "fin5", t: "Bookings, billings, revenue and cash", lvl: "P", k: ["Bookings are signed; billings are invoiced; revenue is earned; cash is received", "Executives conflate these constantly, and the gap hides risk", "Backlog is booked work not yet recognised", "Ask which of the four a number refers to before reacting to it"], do: "Order the four for a three-year contract billed annually in advance." },
        { id: "fin6", t: "Gross margin and how engineering moves it", lvl: "P", k: ["Cost of revenue includes delivery staff, hosting and third-party licences", "Automation reduces cost of revenue; headcount growth increases it", "Margin improvement is the most defensible engineering business case", "A one-point margin gain on large revenue beats most feature work"], do: "Estimate the margin effect of automating one recurring manual process." },
        { id: "fin7", t: "Capex versus opex", lvl: "P", k: ["Capex is spent once and expensed over years; opex hits immediately", "Cloud shifted technology spend from capex to opex, changing the approval path", "Capex protects near-term operating income; opex preserves flexibility", "Which budget a project draws from often decides whether it happens"], do: "Classify five items in your current technology spend." },
        { id: "fin8", t: "Software capitalisation", lvl: "A", k: ["Development costs in the application phase can be capitalised; research cannot", "Capitalising spreads cost across years and improves current-year profit", "It requires evidence: stage gates, time tracking, project separation", "The rules push architecture toward projects with defensible boundaries"], do: "Split one project's activities into capitalisable and non-capitalisable." },
        { id: "fin9", t: "Unit economics", lvl: "P", k: ["Pick the unit: transaction, tenant, user, invoice, integration run", "Cost per unit exposes what aggregate spend hides", "Unit cost trending down is the strongest platform argument you can make", "If you cannot compute cost per unit, you cannot defend the platform"], do: "Define the right unit for your platform and estimate its current cost." },
        { id: "fin10", t: "Total cost of ownership", lvl: "P", k: ["Licence, infrastructure, implementation, run, support, exit", "Exit cost is routinely ignored and routinely decisive", "Compare over the same horizon or the comparison is dishonest", "Internal effort is a real cost even when no invoice exists"], do: "Build a five-year TCO comparison for one build-versus-buy choice you face." },
        { id: "fin11", t: "Time value of money: NPV, IRR, payback", lvl: "A", k: ["Money now is worth more than money later; discount rate quantifies it", "NPV above zero means it beats the hurdle rate", "IRR is the implied return; payback is how long capital is at risk", "Executives ask for payback first and NPV second"], do: "Compute simple payback for an automation costing 1,000,000 saving 40,000 monthly." },
        { id: "fin12", t: "Writing a business case", lvl: "A", k: ["Problem, options considered, recommendation, cost, benefit, risk, decision needed", "Quantify benefits in the same units finance already uses", "State the do-nothing option honestly; it is sometimes right", "One page for the decision; appendix for the analysis"], do: "Compress one current technical proposal to a single-page business case." },
        { id: "fin13", t: "Budget cycles and annual planning", lvl: "P", k: ["Planning starts months before the year and locks earlier than you expect", "Run-rate versus discretionary spend are argued differently", "Unspent budget is usually lost, which drives bad Q4 behaviour", "Missing the planning window costs a full year of funding"], do: "Find your organisation's planning calendar and mark the input deadline." },
        { id: "fin14", t: "Forecasting and variance analysis", lvl: "A", k: ["Forecast accuracy is trusted more than forecast optimism", "Variance is explained by price, volume or mix", "Repeated favourable variance means the budget was padded", "Explain variance before you are asked, in writing"], do: "Write a three-line variance explanation for a 20 percent cost overrun." },
        { id: "fin15", t: "Fully loaded cost of headcount", lvl: "P", k: ["Salary plus benefits, tax, tooling, facilities, management overhead", "Loaded cost is commonly 1.3 to 1.8 times salary", "Blended rate averages seniority across a delivery team", "Comparing a vendor rate to a salary is a category error"], do: "Estimate the loaded cost of one engineer in your own market." },
        { id: "fin16", t: "Services economics: utilisation and realisation", lvl: "A", k: ["Utilisation is billable hours over available hours", "Realisation is billed value over standard value; discounts destroy it", "Bench cost is fixed while revenue is variable, which drives urgency", "A few points of utilisation moves margin more than most cost cutting"], do: "Compute gross margin for an engineer at 75 percent utilisation and a given bill rate." },
        { id: "fin17", t: "The pyramid and delivery leverage", lvl: "A", k: ["Ratio of junior to senior staff determines cost per delivered hour", "Top-heavy teams deliver quality at unsustainable margin", "Leverage only works if seniors can actually delegate", "Automation changes the achievable pyramid shape, which is the AI argument"], do: "Design a ten-person team shape for a fixed-price engagement and justify it." },
        { id: "fin18", t: "Contract types and risk transfer", lvl: "A", k: ["Time and materials puts risk on the client; fixed price on the vendor", "Outcome and managed-service pricing shifts risk to whoever controls delivery", "Change control is what makes fixed price survivable", "Never accept fixed price on a scope you cannot bound"], do: "Pick the right contract type for a vague discovery engagement and defend it." },
        { id: "fin19", t: "Pricing a deal", lvl: "L", k: ["Cost plus target margin, then tested against what the market will pay", "Contingency covers estimation risk; discount erodes it directly", "Multi-year deals need escalation clauses or margin decays with inflation", "The technical leader's job is defending the estimate, not the discount"], do: "Price a six-month engagement bottom-up and state your walk-away margin." },
        { id: "fin20", t: "FinOps: showback and chargeback", lvl: "P", k: ["Tagging discipline is the precondition for any cost attribution", "Showback informs; chargeback changes behaviour and creates arguments", "Shared costs need an allocation rule agreed before the first bill", "Untagged spend above a few percent invalidates the whole exercise"], do: "Define the minimum tag set you would enforce on every cloud resource." },
        { id: "fin21", t: "FinOps: commitments and rate optimisation", lvl: "A", k: ["Reservations and savings plans trade flexibility for a lower rate", "Commit to the stable baseline, run the variable layer on demand", "Rightsizing and scheduling beat rate discounts on immature estates", "Commitment coverage and utilisation are the two numbers to watch"], do: "Identify which of your workloads are stable enough to commit." },
        { id: "fin22", t: "Cost anomaly governance", lvl: "P", k: ["Budgets with alerts catch runaway spend before the invoice does", "Anomaly detection needs an owner or alerts become noise", "Non-production environments are the usual source of surprise", "A monthly cost review with named owners beats any dashboard"], do: "Set the alert thresholds you would use for a non-production subscription." },
        { id: "fin23", t: "Presenting numbers to a CFO", lvl: "L", k: ["Lead with the number and the decision needed, not the method", "Show the assumption that would change the answer if wrong", "Use their vocabulary: margin, payback, run rate, risk", "Never present a benefit you cannot be measured on later"], do: "Rewrite your last technical update as three sentences a CFO would act on." }
      ]
    },
    {
      id: "biz",
      name: "Running a company by the numbers",
      blurb: "The operator's finance vocabulary. Every lesson carries the formula and a worked example with real figures. This is what gets argued about in a monthly business review.",
      lessons: [
        { id: "bz1", t: "The earnings stack", lvl: "F",
          k: ["Every profit figure is the previous one minus one more category of cost", "Which line someone quotes tells you what they are hiding", "Gross profit is delivery efficiency; EBITDA is operating performance; net income is what shareholders keep", "Two companies with identical revenue can differ fourfold at the net line"],
          f: "Revenue − COGS = Gross profit − Opex = EBITDA − D&A = EBIT − Interest = EBT − Tax = Net income",
          ex: "Revenue ₹100cr, COGS ₹62cr, opex ₹22cr, D&A ₹5cr, interest ₹3cr, tax 25%. Gross ₹38cr (38%), EBITDA ₹16cr (16%), EBIT ₹11cr, EBT ₹8cr, net ₹6cr (6%).",
          do: "Build this stack for your business unit and mark which line you can actually influence." },
        { id: "bz2", t: "EBITDA", lvl: "F",
          k: ["Earnings before interest, tax, depreciation and amortisation", "Strips out financing structure and accounting choices to compare operations", "It is the number valuations, bank covenants and bonus plans are usually built on", "Not a defined accounting measure, so definitions vary between companies"],
          f: "EBITDA = Operating income + Depreciation + Amortisation, or Revenue − COGS − cash operating expenses",
          ex: "EBIT ₹11cr with D&A of ₹5cr gives EBITDA ₹16cr. On ₹100cr revenue that is a 16% EBITDA margin.",
          do: "Find your organisation's reported EBITDA margin and compare it to the last two years." },
        { id: "bz3", t: "Where EBITDA lies to you", lvl: "P",
          k: ["It ignores capex, so asset-heavy businesses look better than they are", "It ignores working capital, so a company can grow EBITDA and run out of cash", "It ignores interest, which matters enormously when debt is expensive", "Lease accounting changes moved rent below the EBITDA line, flattering it further"],
          f: "EBITDA − capex − Δworking capital − interest − tax ≈ cash actually available",
          ex: "EBITDA ₹16cr, capex ₹9cr, receivables up ₹6cr, interest ₹3cr, tax ₹2cr: cash generated is negative ₹4cr despite healthy EBITDA.",
          do: "Take one profitable year in your company and check whether cash actually increased." },
        { id: "bz4", t: "Adjusted EBITDA and add-backs", lvl: "P",
          k: ["One-off costs are excluded to show underlying performance", "Legitimate add-backs: restructuring, litigation settlement, acquisition fees", "Aggressive add-backs: recurring 'one-off' costs, share-based pay, normal churn", "Buyers and lenders scrutinise the add-back schedule line by line"],
          f: "Adjusted EBITDA = EBITDA + non-recurring costs − non-recurring gains",
          ex: "EBITDA ₹16cr plus ₹2cr severance and ₹1cr legal settlement gives adjusted EBITDA ₹19cr — a 19% margin instead of 16%.",
          do: "List which costs in your unit someone could plausibly call one-off, and which are actually recurring." },
        { id: "bz5", t: "Margin benchmarks that matter", lvl: "P",
          k: ["IT services typically runs 20 to 30 percent gross and 12 to 20 percent EBITDA", "Product software runs far higher gross margin but spends it on sales and R&D", "Comparing your margin to the wrong industry produces the wrong conclusion", "Margin trend over four quarters beats any single-quarter figure"],
          f: "Gross margin % = Gross profit ÷ Revenue; EBITDA margin % = EBITDA ÷ Revenue",
          ex: "A services firm at 32% gross and 15% EBITDA is healthy. A product company at those numbers is in trouble.",
          do: "Find the gross and EBITDA margin of two listed firms in your own industry." },
        { id: "bz6", t: "Contribution margin", lvl: "P",
          k: ["Revenue minus variable cost, before any fixed cost or overhead", "Tells you whether one more unit of work is worth taking", "A project can carry positive contribution and still lose money after overhead", "Discount decisions should be tested against contribution, not gross margin"],
          f: "Contribution margin = Revenue − Variable costs; CM ratio = CM ÷ Revenue",
          ex: "A ₹40 lakh project with ₹26 lakh of direct delivery cost contributes ₹14 lakh, a 35% CM ratio, before ₹9 lakh of allocated overhead.",
          do: "Compute contribution for one engagement and see what survives overhead allocation." },
        { id: "bz7", t: "Fixed cost, variable cost, operating leverage", lvl: "P",
          k: ["Fixed cost does not move with volume; variable cost does", "High fixed cost amplifies both profit growth and losses", "Bench staff, licences and facilities are fixed; billable contractors are variable", "Operating leverage explains why a 10% revenue drop can wipe out all profit"],
          f: "Operating leverage = Contribution margin ÷ Operating income; Δ operating income % ≈ leverage × Δ revenue %",
          ex: "CM ₹35cr, operating income ₹11cr gives leverage of 3.2. A 10% revenue fall cuts operating income by roughly 32%.",
          do: "Split your unit's cost base into fixed and variable and compute the leverage." },
        { id: "bz8", t: "Break-even", lvl: "P",
          k: ["The revenue at which contribution exactly covers fixed cost", "Margin of safety is how far current revenue sits above break-even", "New capabilities and new offices are break-even decisions, not strategy decisions", "Rising fixed cost raises break-even permanently; discounts raise it too"],
          f: "Break-even revenue = Fixed costs ÷ Contribution margin ratio; Margin of safety % = (Actual − Break-even) ÷ Actual",
          ex: "Fixed cost ₹24cr at a 35% CM ratio needs ₹68.6cr revenue to break even. At ₹100cr actual, margin of safety is 31%.",
          do: "Compute break-even revenue for a new capability you want to launch." },
        { id: "bz9", t: "The accounting cycle", lvl: "F",
          k: ["Transaction, journal entry, ledger posting, trial balance, adjustments, statements", "The general ledger is the book of record; everything reconciles back to it", "Adjusting entries at period end convert raw activity into accrual accounting", "Closing entries reset income accounts and roll the result into retained earnings"],
          f: "Assets = Liabilities + Equity, maintained at every step",
          ex: "A ₹5 lakh invoice raises the AR ledger and revenue, appears in the trial balance, then lands in the P&L and balance sheet for that period.",
          do: "Trace one recent transaction from source document to the financial statements." },
        { id: "bz10", t: "Trial balance and how errors surface", lvl: "P",
          k: ["A list of every ledger account balance, debits equalling credits", "A balanced trial balance proves arithmetic, not correctness", "Compensating errors, wrong-account postings and omissions all still balance", "Suspense accounts hold what cannot yet be classified and must be cleared"],
          f: "Σ Debits = Σ Credits; Suspense balance should tend to zero",
          ex: "Posting an ₹8 lakh purchase to the wrong expense account leaves the trial balance balanced and the departmental P&L wrong.",
          do: "Name two error types a balanced trial balance would not catch." },
        { id: "bz11", t: "Accrual versus cash accounting", lvl: "F",
          k: ["Accrual records economic events when they occur; cash records money movement", "Statutory reporting uses accrual; survival depends on cash", "The gap between the two is working capital", "Most disagreements between finance and delivery are timing, not disagreement about facts"],
          f: "Accrual profit ± timing differences (receivables, payables, deferred revenue) = cash movement",
          ex: "Work delivered in March and billed in April is March revenue and April cash. Q4 looks profitable while the bank balance has not moved.",
          do: "Identify one month where your unit's revenue and cash collection diverged sharply." },
        { id: "bz12", t: "Accruals, prepayments and provisions", lvl: "P",
          k: ["Accrual: cost incurred, not yet invoiced. Prepayment: paid in advance, not yet consumed", "Provision: a probable future cost that can be estimated but not yet invoiced", "Under-accruing flatters the current period and punishes the next one", "Auditors test estimates hardest because that is where judgement hides"],
          f: "Period expense = Cash paid + Closing accrual − Opening accrual − Closing prepayment + Opening prepayment",
          ex: "₹12 lakh annual licence paid in January: ₹1 lakh monthly expense, with ₹11 lakh sitting as a prepaid asset at the end of January.",
          do: "List the accruals your unit owes at month end that finance would not know about without you." },
        { id: "bz13", t: "Receivables, ageing and bad debt", lvl: "P",
          k: ["Ageing buckets (0-30, 31-60, 61-90, 90+) drive both collections and provisioning", "Provision percentages rise with age because collection probability falls", "Disputed invoices are a delivery problem showing up as a finance problem", "Every day of DSO ties up roughly one day of revenue in cash"],
          f: "DSO = (Average receivables ÷ Revenue) × days in period; Provision = Σ (bucket balance × expected loss rate)",
          ex: "Receivables ₹22cr on ₹100cr annual revenue gives DSO of 80 days. Cutting to 65 days releases about ₹4.1cr of cash permanently.",
          do: "Compute your unit's DSO and find the single largest overdue invoice." },
        { id: "bz14", t: "Payables as a financing decision", lvl: "P",
          k: ["Stretching payables is free financing until it damages supplier relationships", "Early payment discounts often beat any deposit rate on an annualised basis", "DPO shorter than DSO means you are financing your clients", "Payment terms are negotiated once and affect cash for years"],
          f: "DPO = (Average payables ÷ COGS) × days; Annualised discount value = (discount % ÷ (100 − discount %)) × (365 ÷ days saved)",
          ex: "2% for paying 20 days early instead of net 50 is worth about 24.8% annualised — far above any borrowing cost.",
          do: "Check whether your vendors offer early-payment discounts nobody is taking." },
        { id: "bz15", t: "Working capital", lvl: "P",
          k: ["Current assets minus current liabilities: the cash tied up in running the business", "Growth consumes working capital, which is why growing firms run short of cash", "Receivables and unbilled work are the two biggest traps in services", "Working capital release is often larger than any cost-cutting programme"],
          f: "Working capital = Current assets − Current liabilities; Current ratio = CA ÷ CL",
          ex: "CA ₹45cr against CL ₹28cr gives ₹17cr working capital and a current ratio of 1.6. Growing revenue 30% typically demands about ₹5cr more.",
          do: "Estimate how much extra working capital 30% growth would need in your unit." },
        { id: "bz16", t: "Cash conversion cycle", lvl: "A",
          k: ["Days between paying for inputs and collecting from clients", "Shortening it releases cash without touching profit at all", "Negative cycles mean clients fund your operations, which is the strongest position", "Services firms have no inventory, so the cycle is receivables minus payables"],
          f: "CCC = DSO + DIO − DPO",
          ex: "DSO 80, DIO 0, DPO 45 gives a 35-day cycle. On ₹100cr revenue, each day is about ₹0.27cr of trapped cash.",
          do: "Compute your cycle and put a rupee value on removing ten days from it." },
        { id: "bz17", t: "Burn rate and runway", lvl: "P",
          k: ["Net burn is cash out minus cash in, per month", "Runway is how long the current balance lasts at current burn", "Gross burn matters when revenue is unreliable; net burn when it is not", "Runway under nine months changes every decision a leadership team makes"],
          f: "Net burn = Monthly cash out − Monthly cash in; Runway (months) = Cash balance ÷ Net burn",
          ex: "₹18cr cash with net burn of ₹1.5cr a month is a 12-month runway. Cutting burn to ₹1.1cr extends it to about 16 months.",
          do: "Compute the runway of the smallest P&L you have visibility into." },
        { id: "bz18", t: "The thirteen-week cash forecast", lvl: "A",
          k: ["Weekly granularity because monthly averages hide the week you cannot pay salaries", "Built from receipts (AR ageing), disbursements (AP, payroll, tax) and committed spend", "Payroll and statutory dates are fixed; everything else is a lever", "Forecast accuracy improves fast once someone owns the variance"],
          f: "Closing cash = Opening cash + Collections − Payroll − Vendor payments − Tax and statutory − Capex",
          ex: "Opening ₹18cr, collections ₹8cr, payroll ₹5.5cr, vendors ₹3cr, tax ₹1.2cr, capex ₹0.8cr leaves ₹15.5cr — a ₹2.5cr weekly draw.",
          do: "Sketch the six line items your own thirteen-week forecast would need." },
        { id: "bz19", t: "Free cash flow", lvl: "A",
          k: ["The cash left after keeping the business running and its assets maintained", "This is what funds dividends, debt repayment, acquisitions and buybacks", "Capitalising more spend improves profit but does not improve free cash flow", "Investors weigh free cash flow above reported earnings for exactly that reason"],
          f: "FCF = Operating cash flow − Capex; Operating cash flow = Net income + D&A − Δworking capital",
          ex: "Net income ₹6cr, D&A ₹5cr, working capital up ₹4cr, capex ₹3cr: operating cash ₹7cr and free cash flow ₹4cr.",
          do: "Compute free cash flow for one public company and compare it to reported profit." },
        { id: "bz20", t: "Debt, leverage and covenants", lvl: "A",
          k: ["Leverage multiplies returns and multiplies risk in the same proportion", "Interest cover shows whether earnings comfortably service the debt", "Covenants are contractual thresholds; breaching one can make debt repayable immediately", "Technology spending decisions get frozen when a covenant is close"],
          f: "Net debt = Debt − Cash; Leverage = Net debt ÷ EBITDA; Interest cover = EBIT ÷ Interest expense",
          ex: "Net debt ₹48cr on EBITDA ₹16cr is 3.0× leverage. EBIT ₹11cr over ₹3cr interest is 3.7× cover — tight against a typical 3.5× covenant.",
          do: "Find out whether your organisation has leverage covenants and what the threshold is." },
        { id: "bz21", t: "Equity, dilution and the cap table", lvl: "P",
          k: ["Equity is ownership; issuing more shares dilutes existing holders", "Option pools are carved out before a raise, so founders bear the dilution", "Preference terms can matter more than headline valuation", "Your own equity grant is worth understanding in fully diluted terms"],
          f: "Ownership % = Shares held ÷ Fully diluted shares; Post-money valuation = Pre-money + Investment",
          ex: "10,00,000 shares of 1,00,00,000 fully diluted is 10%. A raise issuing 25,00,000 new shares dilutes that to 8%.",
          do: "Convert any equity or option grant you hold into a fully diluted percentage." },
        { id: "bz22", t: "Cost of capital and the hurdle rate", lvl: "A",
          k: ["Capital is never free; the hurdle rate is the minimum acceptable return", "Weighted average cost of capital blends the cost of debt and equity", "Projects below the hurdle destroy value even when they are profitable", "Knowing the hurdle rate lets you self-screen proposals before submitting them"],
          f: "WACC = (E ÷ V × Re) + (D ÷ V × Rd × (1 − tax rate))",
          ex: "70% equity at 14% and 30% debt at 9% with 25% tax gives WACC of about 11.8%. A project returning 10% destroys value.",
          do: "Ask finance for your organisation's hurdle rate and test your last proposal against it." },
        { id: "bz23", t: "Return on capital", lvl: "A",
          k: ["Measures profit earned per rupee of capital employed", "Return above the cost of capital creates value; below it destroys value", "Asset-light services businesses can post very high ROCE", "Comparing ROCE to WACC is the cleanest test of whether a business should exist"],
          f: "ROCE = EBIT ÷ (Total assets − Current liabilities); ROI = (Gain − Cost) ÷ Cost",
          ex: "EBIT ₹11cr on capital employed ₹62cr is 17.7% ROCE against an 11.8% WACC — value creating by about 6 points.",
          do: "Compute ROCE for your business unit using its balance sheet share." },
        { id: "bz24", t: "How companies get valued", lvl: "A",
          k: ["Enterprise value covers the whole business; equity value is what shareholders own", "Multiples are shorthand for growth and risk expectations, nothing more", "Services firms trade on EBITDA multiples; product firms often on revenue multiples", "Each rupee of sustainable EBITDA is worth several rupees of valuation"],
          f: "EV = Market cap + Net debt; EV/EBITDA = EV ÷ EBITDA; Equity value = EV − Net debt",
          ex: "At a 9× multiple, EBITDA ₹16cr implies EV ₹144cr. Less ₹48cr net debt, equity is ₹96cr. Adding ₹2cr of EBITDA adds ₹18cr of value.",
          do: "Convert one automation saving into implied valuation impact at your sector's multiple." },
        { id: "bz25", t: "Budget, forecast and rolling forecast", lvl: "P",
          k: ["Budget is the annual commitment; forecast is the current best estimate", "Rolling forecasts extend a fixed number of quarters and never go stale", "Comparing actual to budget measures commitment; to forecast measures control", "Sandbagging the budget is detected in the second year, not the first"],
          f: "Variance = Actual − Budget; Variance % = Variance ÷ Budget; Forecast accuracy = 1 − |Actual − Forecast| ÷ Actual",
          ex: "Budget ₹24cr against actual ₹27cr is a ₹3cr adverse variance, 12.5% over. Consistent 12% overruns mean the budget process, not the spending, is broken.",
          do: "Compute your unit's forecast accuracy over the last four quarters." },
        { id: "bz26", t: "Cost centres, profit centres and allocations", lvl: "P",
          k: ["Cost centres consume budget; profit centres carry revenue and margin", "Shared cost allocation methods decide which unit looks profitable", "Allocation basis (headcount, revenue, usage) is negotiable and worth negotiating", "Running a cost centre caps your career; owning a profit centre does not"],
          f: "Allocated cost = Shared pool × (Unit driver ÷ Total driver)",
          ex: "₹12cr shared services allocated on headcount: a 120-person unit in a 900-person firm absorbs ₹1.6cr.",
          do: "Find out which allocation basis is used for shared cost in your organisation." },
        { id: "bz27", t: "Productivity metrics", lvl: "P",
          k: ["Revenue per employee is the crudest and most quoted efficiency measure", "It rises through automation, pricing power or offshore leverage", "Gross margin per employee is harder to game than revenue per employee", "Any AI business case ultimately has to move one of these"],
          f: "Revenue per employee = Revenue ÷ Average headcount; Gross profit per employee = Gross profit ÷ Average headcount",
          ex: "₹100cr over 900 people is ₹11.1 lakh per head. Holding headcount while growing to ₹115cr lifts it to ₹12.8 lakh, a 15% gain.",
          do: "Compute revenue per employee for your unit and for one listed competitor." },
        { id: "bz28", t: "Backlog, book-to-bill and pipeline coverage", lvl: "A",
          k: ["Backlog is contracted revenue not yet recognised: the forward visibility", "Book-to-bill above 1.0 means the order book is growing faster than revenue", "Pipeline coverage compares weighted pipeline to the gap still to be closed", "Backlog quality matters: renewable annuity work is not the same as one-off projects"],
          f: "Book-to-bill = New bookings ÷ Revenue recognised; Pipeline coverage = Weighted pipeline ÷ Remaining target",
          ex: "Bookings ₹28cr against revenue ₹25cr is 1.12 book-to-bill. A ₹40cr gap needs roughly ₹120cr of pipeline at 3× coverage.",
          do: "Find your unit's book-to-bill ratio for the last two quarters." },
        { id: "bz29", t: "Attrition cost and bench economics", lvl: "A",
          k: ["Replacement cost runs 50 to 150 percent of annual salary once ramp time is counted", "Bench cost is fully fixed while the revenue it could earn is entirely variable", "A few points of attrition can equal an entire margin improvement programme", "Retention is a financial argument, not only a culture argument"],
          f: "Attrition cost = Exits × (hiring cost + ramp productivity loss + backfill premium); Bench cost = Bench headcount × loaded cost × idle months",
          ex: "60 exits from 900 at ₹9 lakh average replacement cost is ₹5.4cr a year — a third of EBITDA at ₹16cr.",
          do: "Estimate the annual attrition cost of your own team and compare it to your tooling budget." },
        { id: "bz30", t: "The real cost of an employee", lvl: "P",
          k: ["Cost to company far exceeds take-home pay: statutory contributions, gratuity, insurance, tooling, facilities", "Loaded cost typically runs 1.3 to 1.8 times base salary", "Contractor rates look expensive because they already include everything", "Bill rate must cover loaded cost, bench, overhead and target margin"],
          f: "Loaded cost = Base + employer statutory contributions + gratuity accrual + benefits + tooling + allocated facilities and overhead",
          ex: "₹20 lakh base at a 1.5 multiplier is ₹30 lakh loaded, about ₹2,000 per productive hour at 1,500 billable hours.",
          do: "Compute the loaded hourly cost of one engineer on your team." },
        { id: "bz31", t: "Indirect tax and withholding for operators", lvl: "P",
          k: ["Indirect tax collected on sales is offset by credit on purchases; only the difference is paid", "Blocked credits and mismatched vendor filings turn credit into real cost", "Withholding reduces the payment, not the expense, and is claimed later", "Export of services has its own treatment and its own documentation burden"],
          f: "Net indirect tax payable = Output tax on sales − Eligible input tax credit",
          ex: "Output tax ₹18 lakh less eligible input credit ₹11 lakh means ₹7 lakh paid. A vendor failing to file converts ₹2 lakh of credit into cost.",
          do: "Find out who reconciles input credit in your organisation and what the leakage was last quarter." },
        { id: "bz32", t: "The monthly business review pack", lvl: "A",
          k: ["Revenue and margin against budget, cash and receivables, headcount and utilisation, pipeline and backlog, risks", "Numbers first, commentary second, actions with owners third", "Variance without explanation is treated as loss of control", "Whoever writes the pack frames what leadership discusses"],
          f: "Structure: actual vs budget vs prior year, variance %, driver, action, owner, date",
          ex: "Margin 13% against 15% budget: driver is 4 points of extra bench; action is redeployment of six engineers by month end, named owner.",
          do: "Rewrite your last status update in the actual-versus-budget-with-driver format." },
        { id: "bz33", t: "The financial calendar", lvl: "P",
          k: ["Month-end close, quarter close with review, year-end with statutory audit, tax filings throughout", "Budget season runs months before the year starts and locks early", "Audit and quarter-end freeze windows constrain deployments and changes", "Knowing the calendar means asking for money and downtime at the right moment"],
          f: "Monthly close → quarterly review and forecast → annual budget → statutory audit and filings",
          ex: "A migration planned for quarter-end weekend collides with close and will be refused. The same plan two weeks earlier is approved.",
          do: "Mark your organisation's close, quarter-end and budget dates in your own calendar." },
        { id: "bz34", t: "What a board actually asks about", lvl: "L",
          k: ["Growth, margin, cash, risk and the two or three bets that could change the trajectory", "They reason in capital allocation and time, not in architecture", "Every proposal is competing against every other use of the same money", "Bad news early is survivable; bad news late is not"],
          f: "Board framing: what changed, what it costs, what it returns, what could go wrong, what decision is needed today",
          ex: "A platform investment presented as ₹6cr over 18 months, ₹3.5cr annual run-rate saving, 26-month payback, main risk being adoption.",
          do: "Convert one technical initiative into that five-part board framing." },
        { id: "bz35", t: "The dozen numbers to watch", lvl: "L",
          k: ["Revenue and growth, gross margin, EBITDA margin, cash and runway", "DSO, book-to-bill, backlog coverage, utilisation", "Attrition, headcount versus plan, revenue per employee, forecast accuracy", "If you cannot recite roughly where each of these stands, you are not yet operating the business"],
          f: "Twelve metrics: revenue growth %, gross margin %, EBITDA margin %, cash and runway, DSO, book-to-bill, backlog coverage, utilisation %, attrition %, headcount vs plan, revenue per employee, forecast accuracy %",
          ex: "A healthy services quarter: 18% growth, 32% gross, 15% EBITDA, DSO 68, book-to-bill 1.1, utilisation 82%, attrition 14%.",
          do: "Write down your best estimate of all twelve for your own unit, then verify each with finance." }
      ]
    }
  ]
};
