/* Technology track. Vendor-neutral, cloud examples lean Azure.
   lvl: F foundation, P practitioner, A architect, L leader */
window.TRACKS = window.TRACKS || {};
window.TRACKS.tech = {
  id: "tech",
  name: "Technology",
  blurb: "Breadth a technology executive is expected to hold without notice. Enough depth to ask the right question and to know when an answer is wrong.",
  modules: [
    {
      id: "net", name: "Networking", blurb: "The layer that gets blamed first and understood last.",
      lessons: [
        { id: "net1", t: "The layers that matter in practice", lvl: "F", k: ["Link, IP, transport, application is the useful model; seven layers is exam trivia", "Most outages sit at DNS, TLS or routing, not at the wire", "Latency comes from distance and hops; bandwidth does not fix it", "Packet loss and retransmission look like slowness, not failure"], do: "Trace one request from your laptop to a cloud service and name each hop type." },
        { id: "net2", t: "DNS", lvl: "F", k: ["Resolution walks root, TLD, authoritative servers, then caches the answer", "TTL controls how long a mistake lives", "CNAME, A and ALIAS behave differently at a zone apex", "Split-horizon DNS is why it works from one network and not another"], do: "Lower a TTL before a planned cutover and explain why to a non-engineer." },
        { id: "net3", t: "TLS and certificates", lvl: "P", k: ["Handshake proves identity and negotiates a session key", "Chain of trust runs from leaf to intermediate to root", "Expiry, hostname mismatch and missing intermediates cause most failures", "Mutual TLS authenticates both sides and complicates every proxy in the path"], do: "Inspect a certificate chain and identify the intermediate." },
        { id: "net4", t: "Load balancing and proxies", lvl: "P", k: ["Layer 4 balances connections; layer 7 understands the request", "Health probes decide traffic, so a wrong probe path takes down a healthy service", "Sticky sessions are a design smell that survives because state was not externalised", "Reverse proxies terminate TLS, rewrite paths and become single points of failure"], do: "Pick layer 4 or layer 7 for an API gateway and justify it." },
        { id: "net5", t: "Edge, CDN and web application firewall", lvl: "A", k: ["Caching static assets at the edge cuts latency and origin cost", "Caching authenticated dynamic routes leaks one user's data to another", "WAF rules block attacks and legitimate traffic in equal measure at first", "Scope cache rules to explicit static paths, never by exclusion"], do: "Write cache rules for a site with an authenticated dashboard and a public marketing page." },
        { id: "net6", t: "Private networking in cloud", lvl: "A", k: ["Virtual networks, subnets and network security groups form the perimeter", "Private endpoints keep platform services off the public internet", "Peering and hub-spoke topologies centralise egress and inspection", "Overlapping address spaces are the most expensive planning mistake"], do: "Draw a hub-spoke topology for three environments and mark the egress point." }
      ]
    },
    {
      id: "os", name: "Operating systems and Linux", blurb: "What is actually happening under the container.",
      lessons: [
        { id: "os1", t: "Processes, memory and scheduling", lvl: "F", k: ["Processes have isolated address space; threads share it", "Virtual memory, paging and swap explain most mysterious slowdowns", "The out-of-memory killer chooses a victim and it is rarely the culprit", "Context switching has real cost at high concurrency"], do: "Read a process list and identify the top memory consumer and its state." },
        { id: "os2", t: "Filesystems and permissions", lvl: "F", k: ["Inodes, links and mount points explain disk-full errors with free space showing", "Ownership, mode bits and umask decide access", "Open file handles keep deleted files consuming space", "Filesystem choice affects durability and performance under write load"], do: "Explain why deleting a large log file did not free disk space." },
        { id: "os3", t: "Shell and scripting", lvl: "P", k: ["Pipes, redirection and exit codes compose small tools into workflows", "Quoting and word splitting cause most script bugs", "Set strict modes early; fail fast beats silent corruption", "Scripts that touch production need idempotency and dry-run mode"], do: "Write a script that is safe to run twice against the same input." },
        { id: "os4", t: "Services, logs and init", lvl: "P", k: ["Service managers handle start, restart, dependency and resource limits", "Structured logs beat free text once you have more than one machine", "Log rotation prevents the classic disk-full outage", "Exit code and restart policy determine crash-loop behaviour"], do: "Define restart policy and resource limits for a service that leaks memory slowly." },
        { id: "os5", t: "Performance triage", lvl: "A", k: ["Check saturation of CPU, memory, disk and network before reading code", "Load average without core count is meaningless", "IO wait high with low CPU points at storage or a chatty query", "Measure before changing; one variable at a time"], do: "Write your own five-command triage sequence for a slow server." },
        { id: "os6", t: "Containers as operating-system primitives", lvl: "P", k: ["Namespaces isolate view; cgroups limit resources; images layer filesystems", "A container is a process, not a machine", "Base image choice is a security and size decision made once and inherited forever", "Anything written inside a container is gone unless it is on a volume"], do: "Explain to a junior why a container is not a lightweight virtual machine." }
      ]
    },
    {
      id: "db", name: "Databases and data modelling", blurb: "The layer where bad decisions compound quietly for years.",
      lessons: [
        { id: "db1", t: "Relational modelling and normal forms", lvl: "F", k: ["Normalisation removes duplication and update anomalies", "Third normal form is enough for most operational systems", "Denormalise deliberately for read performance, never by accident", "The model outlives the application built on it"], do: "Normalise a flat spreadsheet of orders into three tables." },
        { id: "db2", t: "Keys, constraints and referential integrity", lvl: "F", k: ["Natural versus surrogate keys is a decision with long consequences", "Foreign keys enforce truth the application will otherwise forget", "Unique constraints prevent duplicates that deduplication scripts cannot", "Nullable columns are a modelling statement, not a convenience"], do: "Identify one place your data trusts application code instead of a constraint." },
        { id: "db3", t: "Indexing and query plans", lvl: "P", k: ["Indexes trade write cost and storage for read speed", "Composite index column order determines what it can serve", "Read the plan: seeks, scans, joins, estimated versus actual rows", "Unused indexes are pure cost and they accumulate"], do: "Take one slow query, read its plan, and name the missing or wrong index." },
        { id: "db4", t: "Transactions and isolation levels", lvl: "A", k: ["ACID guarantees hold within a database, not across services", "Isolation levels trade consistency for concurrency: dirty, non-repeatable, phantom reads", "Long transactions hold locks and block everything behind them", "Deadlocks are normal; retry logic is the answer, not longer timeouts"], do: "Choose an isolation level for a financial posting and explain the tradeoff." },
        { id: "db5", t: "Non-relational stores and when they fit", lvl: "P", k: ["Document, key-value, wide-column, graph and time-series solve different shapes", "Schema-on-read moves the problem to every consumer, it does not remove it", "Partition key choice determines scale and hotspots permanently", "Choosing by popularity rather than access pattern is the common failure"], do: "Match three of your own workloads to a store type and justify each." },
        { id: "db6", t: "Replication, sharding and high availability", lvl: "A", k: ["Synchronous replication costs latency; asynchronous risks data loss", "Failover needs a decision maker or you get split brain", "Sharding distributes by key and makes cross-shard queries expensive", "Recovery point and recovery time objectives drive the design, not preference"], do: "State the RPO and RTO your current critical system actually achieves." },
        { id: "db7", t: "Schema migrations at scale", lvl: "A", k: ["Expand, migrate, contract lets schema and code deploy separately", "Adding a nullable column is cheap; changing a type on a large table is not", "Backfills need batching, throttling and resumability", "Every migration needs a tested rollback or a forward fix ready"], do: "Plan a column rename on a hundred-million-row table with no downtime." }
      ]
    },
    {
      id: "dist", name: "Distributed systems", blurb: "Everything that breaks once one machine becomes two.",
      lessons: [
        { id: "dist1", t: "Consistency, availability and partitions", lvl: "P", k: ["Partitions happen; the choice is consistency or availability during one", "Strong, eventual and causal consistency have different application costs", "Most systems are eventually consistent and pretend otherwise", "Users notice inconsistency at the boundaries: search, dashboards, counts"], do: "Pick a consistency model for an order status view and state what users will see." },
        { id: "dist2", t: "Idempotency and delivery guarantees", lvl: "A", k: ["At-least-once delivery is normal; exactly-once end to end is marketing", "Idempotency keys make duplicate processing harmless", "Natural idempotency comes from set operations, not increments", "Financial and messaging systems fail hardest here"], do: "Add idempotency to an operation that currently increments a balance." },
        { id: "dist3", t: "Queues versus streams", lvl: "P", k: ["Queues distribute work and delete on acknowledgement", "Streams retain an ordered log that many consumers read independently", "Ordering guarantees usually apply per partition, not globally", "Choosing a queue when you need replay is a rewrite later"], do: "Decide queue or stream for an audit trail and for a job dispatcher." },
        { id: "dist4", t: "Retries, backoff and circuit breakers", lvl: "P", k: ["Naive retries turn a slow dependency into an outage", "Exponential backoff with jitter prevents synchronised retry storms", "Circuit breakers fail fast and let the dependency recover", "Distinguish retryable from terminal errors or you retry forever"], do: "Define retry policy, backoff and breaker thresholds for one external API." },
        { id: "dist5", t: "Sagas and distributed transactions", lvl: "A", k: ["Two-phase commit does not survive real service boundaries", "Sagas chain local transactions with compensating actions", "Compensation is not rollback; some effects cannot be undone", "State machines make saga status inspectable instead of guessed"], do: "Design compensation for a booking that already sent a confirmation email." },
        { id: "dist6", t: "Caching strategies", lvl: "P", k: ["Cache-aside, read-through and write-through have different failure behaviour", "Invalidation is the hard part; TTL is the honest compromise", "Cache stampede on expiry needs locking or staggered TTLs", "Caching authenticated content by URL alone leaks data between users"], do: "Choose a caching strategy for reference data updated twice a day." },
        { id: "dist7", t: "Rate limiting and backpressure", lvl: "A", k: ["Token bucket and sliding window shape traffic differently", "Limits belong at the edge and again at expensive downstream calls", "Backpressure is telling the caller to slow down, not silently queueing", "Unbounded queues convert a throughput problem into a memory outage"], do: "Set rate limits for a public API with free and paid tiers." }
      ]
    },
    {
      id: "cloud", name: "Cloud and platform", blurb: "Buying compute is easy. Owning a platform is not.",
      lessons: [
        { id: "cl1", t: "Shared responsibility and landing zones", lvl: "P", k: ["The provider secures the cloud; you secure what you put in it", "Landing zones set subscription, network, identity and policy structure up front", "Retrofitting governance costs far more than designing it early", "Management groups and policy carry the guardrails, not documentation"], do: "List which controls are yours and which are the provider's for a managed database." },
        { id: "cl2", t: "Infrastructure as code", lvl: "P", k: ["Declarative definitions make environments reproducible and reviewable", "State files are critical assets and need locking and backup", "Drift between code and reality is inevitable without enforcement", "Modules encode standards better than any wiki page"], do: "Identify one manually created resource in your estate and write its definition." },
        { id: "cl3", t: "Cloud identity and managed identity", lvl: "A", k: ["Workload identity removes secrets from code entirely", "Role assignments should be scoped to the smallest resource that works", "Privileged access should be time-bound and approved, not standing", "Service principal sprawl is an unmanaged security debt"], do: "Replace one stored credential in your systems with a managed identity." },
        { id: "cl4", t: "Choosing compute", lvl: "P", k: ["Virtual machines, containers, serverless and managed platforms trade control for effort", "Cold start, execution limits and concurrency caps decide serverless fit", "Operational cost is staff time, not just the invoice", "Portability arguments usually cost more than the lock-in they avoid"], do: "Pick a compute model for a nightly batch job and for a chatty API." },
        { id: "cl5", t: "Resilience and multi-region", lvl: "A", k: ["Availability zones handle datacentre failure; regions handle regional failure", "Active-active doubles cost and complexity; active-passive needs tested failover", "Data residency and replication lag constrain the topology", "An untested failover plan is a document, not a capability"], do: "State the failover time of your most important system and how you know." },
        { id: "cl6", t: "Cost-aware architecture", lvl: "A", k: ["Egress, cross-zone traffic and idle capacity are the usual surprises", "Serverless is cheap at low volume and expensive at steady high volume", "Storage tiering and lifecycle rules recover meaningful spend", "Design reviews should include a cost estimate or cost is not a requirement"], do: "Estimate monthly cost for one current design before it is built." },
        { id: "cl7", t: "Environment strategy", lvl: "P", k: ["Development, test, staging and production need isolation, not just naming", "Production-like data in lower environments is a breach waiting to be reported", "Ephemeral environments per branch reduce contention", "Non-production spend needs a schedule, otherwise it runs all night"], do: "Define what makes your staging environment trustworthy for release decisions." }
      ]
    },
    {
      id: "int", name: "Integration and APIs", blurb: "The connective tissue, and the place enterprise systems actually fail.",
      lessons: [
        { id: "int1", t: "API design and versioning", lvl: "P", k: ["Resources and verbs beat remote procedure names in HTTP APIs", "Status codes and error bodies are part of the contract", "Version when you break; additive changes need no version", "Pagination, filtering and sorting must be designed, not improvised"], do: "Design the resource model and error shape for one internal API." },
        { id: "int2", t: "API gateways", lvl: "A", k: ["Gateways centralise authentication, throttling, routing and transformation", "Policy in the gateway removes duplicated code from every backend", "The gateway becomes a single point of failure and a deployment bottleneck", "Backend for frontend patterns avoid one API serving contradictory needs"], do: "List which concerns belong in the gateway and which stay in the service." },
        { id: "int3", t: "Event-driven integration", lvl: "A", k: ["Events describe what happened; commands ask for something to happen", "Publishers should not know their subscribers", "Event schema changes break consumers you cannot see", "Ordering, replay and poison messages need explicit answers"], do: "Convert one synchronous call in your estate to an event and list what breaks." },
        { id: "int4", t: "Workflow orchestration and iPaaS", lvl: "P", k: ["Low-code workflows trade transparency and testing for speed of change", "Connector limits, throttling and retry semantics differ per connector", "Version control and promotion are the weak point of visual tooling", "Business logic scattered across hundreds of workflows becomes unmaintainable"], do: "Define naming, ownership and promotion rules for a workflow estate." },
        { id: "int5", t: "Contracts and schema governance", lvl: "A", k: ["Contract-first design surfaces disagreement before code exists", "A schema registry with compatibility rules prevents silent breakage", "Consumer-driven contract tests catch what integration tests miss", "Undocumented fields become dependencies you did not agree to"], do: "Pick one integration and write down its contract as it actually behaves." },
        { id: "int6", t: "Integration observability and replay", lvl: "A", k: ["Correlation identifiers must survive every hop or tracing is fiction", "Dead-letter destinations need an owner and a replay path", "Replay must be idempotent or recovery causes duplicates", "Business-level metrics beat technical ones for integration health"], do: "Trace one end-to-end flow and find where the correlation id is lost." },
        { id: "int7", t: "Legacy and file-based integration", lvl: "P", k: ["File drops, fixed-width formats and batch windows are still everywhere", "Idempotency comes from filename conventions and processed-file registers", "Partial-file reads are a real failure mode; use atomic moves", "Batch to real-time migration usually needs both running in parallel first"], do: "Design safe pickup for a directory a partner writes to unpredictably." }
      ]
    },
    {
      id: "sec", name: "Security and identity", blurb: "The area where a technology leader is personally accountable.",
      lessons: [
        { id: "sec1", t: "Threat modelling", lvl: "P", k: ["Ask what can go wrong per component, not in general", "Spoofing, tampering, repudiation, disclosure, denial, elevation is a usable checklist", "Trust boundaries are where the interesting threats live", "A threat model that produces no design change was not a threat model"], do: "Threat model one system you own and record two design changes." },
        { id: "sec2", t: "Authentication protocols", lvl: "P", k: ["OAuth 2 authorises; OpenID Connect authenticates; SAML predates both", "Tokens carry claims; validate signature, issuer, audience and expiry", "Refresh tokens are long-lived credentials and must be protected as such", "Implicit flow is dead; use authorization code with PKCE"], do: "Draw the authorization code flow from memory and check it." },
        { id: "sec3", t: "Authorisation models", lvl: "A", k: ["Role-based is simple; attribute-based scales to conditional rules", "Authorisation belongs in the service, not only in the user interface", "Multi-tenant systems need tenant isolation enforced at data access", "Permission creep is a lifecycle problem, not a design problem"], do: "Write the authorisation rule for one endpoint in plain language, then in policy." },
        { id: "sec4", t: "Secrets management", lvl: "P", k: ["Secrets belong in a vault with access policy and audit, never in code or config files", "Rotation must be automated or it does not happen", "Managed identity removes the secret entirely where supported", "Committed secrets stay in git history after deletion"], do: "Audit one repository for secrets, including its history." },
        { id: "sec5", t: "Zero trust and least privilege", lvl: "A", k: ["Verify explicitly, assume breach, grant least privilege", "Network location is not an authorisation decision", "Standing administrative access is the largest avoidable risk", "Just-in-time elevation with approval balances control and speed"], do: "Find one standing privileged role in your estate and time-bound it." },
        { id: "sec6", t: "Application security", lvl: "P", k: ["Injection, broken access control and misconfiguration dominate real incidents", "Dependency vulnerabilities enter through the supply chain, not your code", "Static and dynamic scanning belong in the pipeline, with a failure threshold", "Security review at the end is a scheduling device, not a control"], do: "Add one automated security gate to a pipeline you control." },
        { id: "sec7", t: "Incident response", lvl: "A", k: ["Detect, contain, eradicate, recover, learn, in that order", "Evidence preservation comes before cleanup if breach is possible", "Communication plans include legal, clients and regulators, not just engineers", "Practised response is the difference between an incident and a crisis"], do: "Write the first thirty minutes of your response to a credential leak." },
        { id: "sec8", t: "Data protection and privacy", lvl: "A", k: ["Classify data before designing controls for it", "Encryption at rest and in transit is table stakes; key custody is the real question", "Retention and deletion obligations are engineering requirements", "Cross-border data movement is a contractual and legal constraint"], do: "Classify the data in one system and state its retention rule." }
      ]
    },
    {
      id: "devops", name: "Delivery and DevOps", blurb: "How work reaches production, and how fast you can undo it.",
      lessons: [
        { id: "do1", t: "Version control strategy", lvl: "F", k: ["Trunk-based development with short-lived branches suits continuous delivery", "Long-lived branches create merge debt that surfaces at the worst time", "Protected branches and required reviews encode the policy", "Commit history is documentation for the next maintainer"], do: "State your branching model and the maximum branch age you will allow." },
        { id: "do2", t: "Continuous integration", lvl: "P", k: ["Every commit builds and tests, or integration is not continuous", "Build time above ten minutes changes developer behaviour for the worse", "Flaky tests destroy trust faster than missing tests", "Artifacts are built once and promoted, never rebuilt per environment"], do: "Measure your current build time and name the slowest stage." },
        { id: "do3", t: "Deployment strategies", lvl: "P", k: ["Rolling, blue-green and canary trade cost against blast radius", "Feature flags separate deploy from release", "Database changes are the reason rollback is often impossible", "Deployment should be boring enough to happen on a Friday"], do: "Choose a deployment strategy for a stateful service and state the rollback plan." },
        { id: "do4", t: "Configuration and environment promotion", lvl: "P", k: ["Configuration lives outside the artifact", "Environment differences should be data, not separate code paths", "Secrets are injected at runtime, never baked into images", "The same pipeline promotes to every environment or staging proves nothing"], do: "Find one setting that differs between environments in code rather than config." },
        { id: "do5", t: "Testing strategy", lvl: "P", k: ["Unit, integration, contract and end-to-end each catch different failures", "End-to-end tests are the most expensive and least reliable; use few", "Test data management is usually the real blocker", "Coverage percentage measures effort, not safety"], do: "Map your current tests to the four types and find the missing layer." },
        { id: "do6", t: "Delivery metrics", lvl: "A", k: ["Deployment frequency, lead time, change failure rate, restoration time", "These four correlate with organisational performance and are hard to game together", "Measure the system, not individuals, or the numbers become fiction", "Improving lead time usually requires reducing batch size first"], do: "Estimate all four metrics for your team and mark which you cannot measure." }
      ]
    },
    {
      id: "obs", name: "Observability and operations", blurb: "Knowing what production is doing before a client tells you.",
      lessons: [
        { id: "ob1", t: "Logs, metrics and traces", lvl: "F", k: ["Logs describe events, metrics aggregate, traces follow a request across services", "Structured logs are queryable; free text is archaeology", "Cardinality kills metrics systems and inflates bills", "Retention policy is a cost decision made deliberately or accidentally"], do: "Pick one recent incident and state which signal would have caught it earliest." },
        { id: "ob2", t: "Distributed tracing and correlation", lvl: "A", k: ["A trace id propagates through every hop including queues and workflows", "Spans show where time is actually spent", "Sampling reduces cost but hides rare failures; sample errors fully", "Instrumentation gaps make traces confidently wrong"], do: "Follow one transaction across three systems and note where the trace breaks." },
        { id: "ob3", t: "Service level objectives", lvl: "A", k: ["Indicators measure; objectives target; agreements carry contractual consequence", "Error budgets convert reliability into a spending decision", "Objectives should reflect user experience, not server health", "One hundred percent is not a target, it is a refusal to prioritise"], do: "Write one SLO with an indicator, target and measurement window." },
        { id: "ob4", t: "Alerting and on-call", lvl: "A", k: ["Alert on symptoms users feel, not on every threshold breach", "Every alert needs an action; if there is none, it is a dashboard", "Alert fatigue is a reliability risk, not a morale issue", "On-call needs rotation, compensation, escalation and handover"], do: "Delete or downgrade three alerts that have never led to action." },
        { id: "ob5", t: "Incident command", lvl: "A", k: ["One incident commander decides; everyone else executes or observes", "Communication cadence is separate from technical work", "Mitigate first, diagnose second, unless diagnosis is the only route to mitigation", "Timeline capture during the incident makes the review honest"], do: "Define roles and communication cadence for your next major incident." },
        { id: "ob6", t: "Postmortems and learning", lvl: "L", k: ["Blameless review finds systemic causes; blame finds a scapegoat and stops", "Contributing factors are plural; single root cause is usually a simplification", "Actions need owners, dates and follow-up or nothing changes", "Repeat incidents mean the previous review failed"], do: "Reopen your last postmortem and check whether the actions actually closed." }
      ]
    },
    {
      id: "data", name: "Data and analytics platform", blurb: "Where operational systems become decisions.",
      lessons: [
        { id: "da1", t: "Operational versus analytical workloads", lvl: "F", k: ["Transactional systems optimise for many small writes; analytical for large reads", "Reporting directly off production is the first mistake most estates make", "Column stores compress and scan differently from row stores", "Separating the two changes both cost and access control"], do: "Find one report currently running against a production transactional database." },
        { id: "da2", t: "Lakehouse and layered architecture", lvl: "A", k: ["Raw, cleaned and curated layers separate ingestion from consumption", "The raw layer is immutable history and enables reprocessing", "Curated tables serve business definitions, not source system structures", "Skipping layers to save time creates the coupling you were avoiding"], do: "Assign three of your current tables to raw, cleaned or curated." },
        { id: "da3", t: "ELT, ETL and ingestion patterns", lvl: "P", k: ["Extract-load-transform pushes work to the warehouse; ETL transforms first", "Full versus incremental load depends on change detection in the source", "Change data capture avoids polling and preserves deletes", "Late-arriving and out-of-order data must be designed for, not discovered"], do: "Choose full or incremental load for one source and state how you detect change." },
        { id: "da4", t: "Dimensional modelling", lvl: "P", k: ["Facts hold measures; dimensions hold context", "Grain is declared first and everything else follows from it", "Slowly changing dimensions preserve history of attributes that change", "Star schemas remain the most understandable model for business users"], do: "Declare the grain of one fact table you would build for delivery revenue." },
        { id: "da5", t: "Data quality and lineage", lvl: "A", k: ["Completeness, accuracy, timeliness, uniqueness, consistency are testable", "Quality checks belong in the pipeline with a defined failure action", "Lineage answers where a number came from, which is the first audit question", "Nobody trusts a dashboard that was once wrong and never explained"], do: "Write three quality tests for one critical table." },
        { id: "da6", t: "Semantic layer and governed metrics", lvl: "A", k: ["One definition of revenue, headcount and margin, or reports will disagree", "Metric definitions belong in version control, not in individual reports", "Row-level security enforces who sees which slice of the same table", "Self-service without governance produces confident contradiction"], do: "Find two reports in your organisation that define the same metric differently." },
        { id: "da7", t: "Data products and ownership", lvl: "L", k: ["Datasets need an owner, a contract, a service level and a consumer list", "Domain ownership scales better than a central team owning everything", "Discovery and documentation are part of the product, not extras", "Without ownership, quality decays to the level nobody complains about"], do: "Name the owner of your most-used dataset. If you cannot, that is the finding." }
      ]
    },
    {
      id: "ai", name: "AI and LLM engineering", blurb: "The current bet. Understand the economics, not just the demos.",
      lessons: [
        { id: "ai1", t: "How language models actually behave", lvl: "F", k: ["Tokens, context windows and next-token prediction explain most surprises", "Models are confident regardless of correctness", "Temperature and sampling control variability, not accuracy", "Knowledge cutoffs and hallucination are properties, not bugs to patch"], do: "Explain to a business stakeholder why the model invented a plausible answer." },
        { id: "ai2", t: "Prompting and structured output", lvl: "P", k: ["Clear instructions, examples and explicit output format beat clever phrasing", "Structured output with a schema makes responses programmatically usable", "System instructions set persistent behaviour; user turns set the task", "Prompt changes need regression testing like any other code"], do: "Rewrite one prompt to return strict structured output and test five inputs." },
        { id: "ai3", t: "Retrieval-augmented generation", lvl: "A", k: ["Retrieval quality dominates output quality; the model is rarely the bottleneck", "Chunking strategy, embedding choice and reranking each move accuracy", "Hybrid keyword and vector search outperforms either alone in enterprise data", "Access control must be applied at retrieval, not in the prompt"], do: "Take ten real questions and measure whether the right document is retrieved." },
        { id: "ai4", t: "Agents and tool use", lvl: "A", k: ["An agent is a loop: decide, call a tool, observe, repeat", "Tool descriptions are prompts and deserve the same care", "Bound the loop with step limits, budgets and timeouts", "Failure modes are silent wrong actions, not error messages"], do: "Define the stopping conditions and spend cap for one agent workflow." },
        { id: "ai5", t: "Tool protocols and integration surface", lvl: "A", k: ["Standard tool protocols decouple model choice from tool implementation", "Every exposed tool is an attack surface and a permission decision", "Read tools are safer than write tools; separate them explicitly", "Untrusted content entering a context can carry instructions"], do: "Split one agent's tools into read and write and gate the write path." },
        { id: "ai6", t: "Evaluation and guardrails", lvl: "A", k: ["Without an evaluation set you are tuning by anecdote", "Build the eval set from real failures before optimising anything", "Automated scoring plus human review on a sample is the workable compromise", "Guardrails handle the cases evaluation proves you cannot fix in the prompt"], do: "Build a twenty-case evaluation set for one AI feature you run." },
        { id: "ai7", t: "Cost and latency engineering", lvl: "A", k: ["Input tokens usually dominate cost; context bloat is the main leak", "Prompt caching cuts cost sharply on repeated stable prefixes", "Model routing sends easy work to smaller models", "Streaming improves perceived latency without improving actual latency"], do: "Compute cost per request for one AI feature and find the largest token contributor." },
        { id: "ai8", t: "AI strategy and adoption", lvl: "L", k: ["Value comes from the workflow redesigned around the model, not the model", "Adoption fails on trust and process, not capability", "Measure task completion and cycle time, not usage counts", "Every deployment needs a named owner for when it is wrong"], do: "Pick one workflow and state the metric that would prove AI improved it." }
      ]
    },
    {
      id: "gov", name: "Architecture governance and technology management", blurb: "How technical decisions survive people leaving.",
      lessons: [
        { id: "gv1", t: "Architecture decision records", lvl: "P", k: ["Record context, options, decision and consequences, in that order", "The rejected options are the most valuable part later", "Records are immutable; new decisions supersede rather than edit", "Decisions without records get relitigated every eighteen months"], do: "Write a record for a decision you made last month, including what you rejected." },
        { id: "gv2", t: "Reference architectures and standards", lvl: "A", k: ["Standards constrain choice to reduce variety cost", "Golden paths work better than mandates because they are easier than the alternative", "Every standard needs an exception process or it will be ignored", "Unenforced standards are worse than none; they create false assurance"], do: "Write one standard with its exception path in under a page." },
        { id: "gv3", t: "The enterprise architecture function", lvl: "A", k: ["Business, data, application and technology architecture are separate views", "Heavy frameworks fail in delivery organisations; take the vocabulary, not the ceremony", "Architecture that does not touch delivery decisions is documentation", "Capability maps connect technology spend to business function"], do: "Map three of your systems to the business capabilities they support." },
        { id: "gv4", t: "Risk and compliance frameworks", lvl: "A", k: ["Certifications like ISO 27001 and SOC 2 test controls and their evidence", "Controls need owners, evidence and periodic testing", "Client contracts often impose stricter terms than any certification", "Compliance is a floor for security, never a ceiling"], do: "Pick one control you own and locate the evidence it operated last quarter." },
        { id: "gv5", t: "Vendor and licence management", lvl: "L", k: ["Licence models by user, core, transaction or consumption change TCO materially", "Renewal dates are negotiation leverage if you prepare early", "Exit clauses and data extraction rights matter more than feature lists", "Shadow purchasing fragments spend and loses volume discounts"], do: "List your top five vendors with renewal dates and the exit path for each." },
        { id: "gv6", t: "Technology radar and lifecycle", lvl: "L", k: ["Adopt, trial, assess, hold gives a shared vocabulary for maturity", "Deprecation needs a date, an owner and a migration path", "Technology accumulates unless removal is somebody's explicit job", "Publishing the radar is how standards spread without enforcement"], do: "Place five technologies you use in adopt, trial, assess or hold." },
        { id: "gv7", t: "Technical debt as a financial argument", lvl: "L", k: ["Debt has a principal, an interest rate and a payoff date", "Express debt as recurring cost or risk exposure, not as engineer discomfort", "Some debt should never be repaid; state that explicitly", "A debt register with owners beats a complaint in a retrospective"], do: "Quantify one piece of technical debt as annual cost or risk exposure." }
      ]
    }
  ]
};
